name: Docker CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myapp .
          docker images

      - name: Test application
        run: |
          docker run -d --name testapp -p 5000:5000 myapp
          sleep 5
          
          echo "=== Checking container status ==="
          docker ps -a
          
          echo "=== Application logs ==="
          docker logs testapp
          
          echo "=== Testing response ==="
          response=$(curl -s http://localhost:5000)
          echo "Server response: '$response'"
          
          if [ "$response" == "Hello, Docker CI/CD!" ]; then
            echo "✓ Test passed"
            docker stop testapp
            exit 0
          else
            echo "✗ Test failed: unexpected response"
            docker stop testapp
            exit 1
          fi
