name: Docker CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Run tests
        run: |
          docker run -d --name testapp -p 5000:5000 myapp
          timeout 30 bash -c 'while ! curl -s http://localhost:5000; do sleep 1; done'
          curl -s http://localhost:5000 | grep -q "Hello, Docker" || (echo "Тест не пройден" && exit 1)
          echo "Тест пройден успешно!"
          docker stop testapp

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker tag myapp ${{ secrets.DOCKER_USER }}/myapp:latest
          docker push ${{ secrets.DOCKER_USER }}/myapp:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/myapp:latest
            docker stop myapp || true
            docker run -d -p 5000:5000 --name myapp ${{ secrets.DOCKER_USER }}/myapp:latest
