name: Simple Docker CI/CD

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      run: |
        docker build -t myapp .
        
        docker run -d --name myapp -p 5000:5000 myapp
        sleep 5
        
        docker ps -a
        docker logs myapp
        
        curl -s http://localhost:5000 || echo "App failed"
        
        docker stop myapp
