name: Docker CI/CD Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t myapp .
        
    - name: Test container
      run: |
        docker run -d --name testapp -p 5000:5000 myapp
        sleep 5
        
        docker logs testapp
        
        curl -s http://localhost:5000 || echo "App test failed"
