name: Docker CI/CD Test

on: 
  push:
    branches: [ myapp ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myapp .
          docker run --rm -d -p 5000:5000 --name testapp myapp
          sleep 5
          docker ps -a
          docker logs testapp
          curl -v http://localhost:5000 || true
          docker stop testapp
