name: Docker CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t myapp .
        docker images

    - name: Test container
      run: |
        # Запускаем контейнер с подключением терминала
        docker run --name testapp -p 5000:5000 -d myapp
        
        # Ждем 5 секунд перед проверкой
        sleep 5
        
        # Проверяем состояние контейнера
        echo "=== Container Status ==="
        docker ps -a
        echo "=== Container Logs ==="
        docker logs testapp
        
        # Проверяем доступность приложения
        echo "=== Testing Application ==="
        if curl -s http://localhost:5000 | grep "Hello, Docker"; then
          echo "Application test passed!"
          docker stop testapp
          exit 0
        else
          echo "::error::Application test failed"
          docker stop testapp
          exit 1
        fi

    - name: Save image
      if: success()
      run: docker save myapp -o myapp.tar

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/download-artifact@v4
      with:
        name: myapp-image
        path: .

    - name: Load image
      run: docker load -i myapp.tar

    - name: Deploy to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker tag myapp ${{ secrets.DOCKER_USER }}/myapp:latest
        docker push ${{ secrets.DOCKER_USER }}/myapp:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USER }}/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 5000:5000 --name myapp ${{ secrets.DOCKER_USER }}/myapp:latest
