name: Hello, Docker + GitHub Actions!

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t myapp .
        
    - name: Test container
      run: |
        docker build -t myapp .
        docker run -d --name testapp -p 5000:5000 myapp
        sleep 10
        docker logs testapp
        curl -v http://localhost:5000 | grep "Hello, Docker CI/CD" || (echo "Test failed" && exit 1)
